version: '3'
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:alpine
    restart: always
    user: root
    environment:
      - "JAVA_OPTS=-Xmx512M -Xms256M"
    ports:
      - 8080:8080
    volumes:
      - /opt/jenkins:/var/jenkins_home
    links:
      - jenkins-agent

  jenkins-agent:
    container_name: jenkins-agent
    image: sancraftdev/jenkins-ssh-agent
#    image: sancraftdev/jenkins-ssh-agent:alpine # only works on arm64
    environment:
      - "JENKINS_AGENT_SSH_PUBKEY=ssh-rsa ABCDEFGHIJKLMNOPQRSTUVWXYZ"
    restart: always
